name: Code Analysis Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Run code analysis
        run: |
          dotnet format --check --severity error source/repos/LogiWereHubSite2/LogiWereHubSite2/LogiWereHubSite2.csproj
