name: Code Analysis Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install StyleCop Analyzers
        run: |
          cd source/repos/LogiWereHubSite2/LogiWereHubSite2
          dotnet add package StyleCop.Analyzers --version 1.1.118


      - name: Build project with StyleCop
        run: dotnet build source/repos/LogiWereHubSite2/LogiWereHubSite2/LogiWereHubSite2.csproj /p:StyleCopEnabled=true /p:StyleCopTreatErrorsAsWarnings=true

